### PR TITLE
Lower minimum Ruby version to 1.9.3.

### PR DESCRIPTION
**Pull request by nning**
Is there any reason, 2.0.0 is specified as minimum Ruby version? Specs work for me in JRuby in 1.9 mode and in a quick review, I could not find any code specific to >= 2.0.0.

### CODE REVIEW

**Comment by nning** [comment]
Specs are working in MRI 1.9.3-p551, too.

**Comment by prodis** [comment]
Test environment is broken in ruby 1.9.3p551 according Travis. 
https://travis-ci.org/prodis/wannabe_bool/jobs/103309389

@nning, can you solve this?
Please put JRuby versions that you use in .travis.yml too.

Thank you.

**Comment by prodis** [comment]
@nning Solved with 0.5.0 version.

Please give me a feedback if works for you.

**Comment by nning** [comment]
Yes, it does. Thanks!

**Pull request closed without merging**
